### ISSUE TITLE
No Results

### ISSUE THREAD

**Issue by wuchenhu98** [d-ailin/GDN#100]
Hello,i can run the model successfully,but i only got the following result
![result1](https://github.com/d-ailin/GDN/assets/114411779/558813ac-16a1-40dd-8897-617e3445541e)
there is no file in the Results folder

**Comment by d-ailin** [comment]
Hi, thanks for your interest. 

The current code does not save the predicted values for test data but only output the final evaluation metrics, e.g., F1 score. To save the result, you could modify the code to save the test result:

https://github.com/d-ailin/GDN/blob/9853899da860682669a134e4af315d036aab4eca/main.py#L123

**Comment by wuchenhu98** [comment]
Thanks a lot!
