### ISSUE TITLE
Reproduce the results and Dataset Problems

### ISSUE THREAD

**Issue by UppSun** [d-ailin/GDN#11]
Hello, your work is interesting and impressive, which is very useful to me.
I reproduced the SWaT and WADI results, but there were some problems.

1. For SWaT, I used SWAT_Dataset_normal_v0.xlsx and SWaT_Dataset_attack_v0.xlsx, and for WADI,I am using 2019 WADI_14days_new.csv and 2019WADI_attackdatalable.csv, Did you also train on those files?
2. I have done the min_max normalization and downsample according to the previous issues and reproduced your results, but they are inconsistent with the results of the paper.

Here are the results of the SWaT dataset:
F1 score: 0.7717
Precision: 0.9717
Recall: 0.6398
Auc: 0.8517

Here are the results of the WADI dataset:
F1 score: 0.2442
Precision: 0.2052
Recall: 0.3019
Auc: 0.7083

There is a big gap between the results of WADI and the paper. I tried multiple random seeds, but the results were similar.In addition, AUC is higher than pre and Recall. Is this normal?
Any suggestions would be appreciated!Thank you very much!

**Comment by d-ailin** [comment]
I think it might be caused by the dataset preprocessing. 
No worry, I would upload the key preprocessing code and some preprocessed data to help later this week.

**Comment by d-ailin** [comment]
Hi UppSun, I have uploaded some main scripts and readme for the datasets and maybe you could then check with them.
Thanks.

**Comment by meihuameii** [comment]
> Hello, your work is interesting and impressive, which is very useful to me. I reproduced the SWaT and WADI results, but there were some problems.
> 
> 1. For SWaT, I used SWAT_Dataset_normal_v0.xlsx and SWaT_Dataset_attack_v0.xlsx, and for WADI,I am using 2019 WADI_14days_new.csv and 2019WADI_attackdatalable.csv, Did you also train on those files?
> 2. I have done the min_max normalization and downsample according to the previous issues and reproduced your results, but they are inconsistent with the results of the paper.
> 
> Here are the results of the SWaT dataset: F1 score: 0.7717 Precision: 0.9717 Recall: 0.6398 Auc: 0.8517
> 
> Here are the results of the WADI dataset: F1 score: 0.2442 Precision: 0.2052 Recall: 0.3019 Auc: 0.7083
> 
> There is a big gap between the results of WADI and the paper. I tried multiple random seeds, but the results were similar.In addition, AUC is higher than pre and Recall. Is this normal? Any suggestions would be appreciated!Thank you very much!

@UppSun Hello!  What threshold selection strategy do you use? "report==val" or report=best?
