### ISSUE TITLE
The results on SWaT

### ISSUE THREAD

**Issue by chenxino** [d-ailin/GDN#12]
Thank you very much for sharing the code. According to the paper, I preprocessed the  SWaT data, and then ran the code to get the following results：
F1 score: 0.7710816777041943
precision: 0.9705391884380211
recall: 0.6394433253982788.
And the command for running the code is 
···
python main.py -dataset SWaT \
        -save_path_pattern SWaT \
        -slide_stride 1 \
        -slide_win 5 \
        -batch 16 \
        -epoch 30 \
        -comment SWaT \
        -random_seed 6799 \
        -decay 0 \
        -dim 64 \
        -out_layer_num 1 \
        -out_layer_inter_dim 1 \
        -val_ratio 0.1 \
        -report best \
        -topk 15.
···
In addition, I have the use of the verification to select the threshold and set '-report' to 'val', get 
F1 score: 0.5206937055206247
precision: 0.4181091877496671
recall: 0.6899835195019227.
 So whether my parameter setting and preprocessing are correct, if they are correct, and what I should do to further improve the accuracy. Thanks!

**Comment by d-ailin** [comment]
Hi chenxino, you could refer to the scripts directory for more details. Thanks.

**Comment by chenxino** [comment]
Thank you for your reply.
