### ISSUE TITLE
evaluation method

### ISSUE THREAD

**Issue by giraffe2021-12** [d-ailin/GDN#13]
Hello, thank you for sharing your work, it is interesting and impressive. But I am confused about the evaluation method you used. You calculated scores with test_result and val_result, both include predicted, ground, labels. That's very confused me. why don't you compare the predicted labels with the original labels directly? 
By the way, I ran your code and got very high scores when I set '-report=='best'' as follows. Even I change the seed value, it does not change.
F1 score_best: 0.9430060816681147
precision_best: 0.9428323197219809
recall_best: 0.9428323197219809

On the other hand, when I set '-report=='val'', I got very low scores like this:
F1 score_val: 0.01320590790616855
precision_val: 0.01320590790616855
recall_val: 0.01320590790616855
when I change seed value, the scores change a little but still very slow.

Could you tell me why? Thank you very much!

**Comment by d-ailin** [comment]
Hi, thanks for your interest! 
For the evaluation, we need to choose a threshold to decide the decision label as the model is predicting the value for the time steps and requires a threshold to decide labels(normal or anomaly). Hence, when you set '-report' as 'val', the threshold we choose here is based on the validation set. Besides, we provide another threshold choosing with 'best', which is using the best result across the different thresholds.

If you get a low result using 'val', it may indicate the validation set is not good then you could reset the parameter `val_ratio` to adapt the validation set size for your dataset. Also, using the different seed values can result in different splits of validation, which can also help.

**Comment by giraffe2021-12** [comment]
Thank you for your reply. I reset the val_ratio=0.3, but the scores are still low (F1_val=0.018). so I want to know how did you set your parameters when you got the results reported in your paper. Di you set -report=best or val?. I also plot predicted results of test_result and val_result and compare them with ground_results. I found that the predicted data differs from the ground data significantly, even I got high scores of F1=0.94 on test.

**Comment by d-ailin** [comment]
We use the validation set to choose a threshold. As the anomalies are based on the larger deviation differences, it means as long as the predictions from anomaly time steps perform more deviated compared to the normal time steps', it could detect anomalies well. Hence, the case you describe might happen. But I think it is important to reset some parameters or pre-process(e.g. normalize) for your custom dataset to have a good prediction first.

Hope this helps, thanks.

**Comment by m-ali-awan** [comment]
Hi @d-ailin, hope you are fine.
I am working on anomaly detection on Multivariate Time Series using the SwaT dataset. Only a normal dataset is going to be used for training, named as " SWaT_Dataset_Normal_v0".
The end goal is creating GAN + graph attention networks or GAN+ graph transformers for anomaly detection.

Related work along with code can be found here:
https://www.dropbox.com/sh/2f0qb2raeftqqxf/AABQRnAGrc5CRjttS6ZI-_H4a?dl=0

 

So, if you think that you have some time to help me with this, I would be grateful. If you can find some time for a meeting, so we can discuss how can we proceed.

Thanks,
Best Regards,
Muhammad Ali.
