### ISSUE TITLE
Reproduce problem on dataset

### ISSUE THREAD

**Issue by ly1112** [d-ailin/GDN#14]
Hello, thank you for sharing your work, it is interesting.  But when I am trying to reproduce your work on SWAT dataset. I am quite confused about which subset you use to get the results on your paper? Only A1&A2 and I check the original SWaT_Dataset_Normal_v0.xlsx file has 496801 samples, not the one you mentioned in your paper which is 47515. Thanks a lot and looking forward to your reply.

**Comment by d-ailin** [comment]
The data statistic shown in the paper is after preprocessing, which includes excluding the unstable system warm-up data and downsampling. You could also try to run the process script in the scripts directory to get the processed data.
