### ISSUE TITLE
Questions about the experiment

### ISSUE THREAD

**Issue by Jsok00** [d-ailin/GDN#19]
Hello. 
We are recently studying the problem of anomaly detection based on time-series data, and in the process of our research, we found your paper, and we are very interested in your GDN model, thank you for sharing it. 

We are currently reproducing your GDN model, and the results are very good on the SWaT dataset, but not so good on the WADI dataset (f1:0.45, pre:0.886, recall:0.303), so I would like to ask you what is wrong with my reproduction experiments, and I hope I can get your help. Again, thank you.

**Comment by d-ailin** [comment]
Hi, thanks for your interest in our work.

I guess it might due to the difference of preprocessing and hyperparameter setting.

We have provided the preprocessing scripts: https://github.com/d-ailin/GDN/tree/main/scripts. Also, you could refer to #17 for the hyperparameter setting.

**Comment by d-ailin** [comment]
Feel free to reopen the issue if there is any further question.
