### ISSUE TITLE
Expected a value of type 'Optional[Tensor]' for argument 'ptr' but instead found type 'int'.

### ISSUE THREAD

**Issue by Scienceseb** [d-ailin/GDN#20]
Hello I get the same error:

```
RuntimeError: softmax() Expected a value of type 'Optional[Tensor]' for argument 'ptr' but instead found type 'int'.
Position: 2
Value: 48
Declaration: softmax(Tensor src, Tensor? index=None, Tensor? ptr=None, int? num_nodes=None, int dim=0) -> (Tensor)
Cast error details: Unable to cast Python instance to C++ type (compile in debug mode for details)

```

Why the code cannot work with my environment ? It is the first time I ever encounter that type of error... I have  CUDA 11.3 and PyTorch 1.10.2. 

Thanks for your help !

_Originally posted by @Scienceseb in https://github.com/d-ailin/GDN/issues/10#issuecomment-1076489776_

**Comment by d-ailin** [comment]
I think the best way is to run the code with a virtual environment with same environmental setting (package' version) provided in the repo. 

Also, you could refer to some previous issue #2. It seems it could work out by modifying some code (but I am not quite sure about the effect).

**Comment by Scienceseb** [comment]
The fix is the following:

1) 
In graph_layer.py
```
self.node_dim=0
alpha = softmax(alpha, edge_index_i, num_nodes=size_i)

```

2) Error with dataloader: https://stackoverflow.com/questions/70193443/colab-notebook-cannot-import-name-container-abcs-from-torch-six
