### ISSUE TITLE
Why don't you normalize the input data?

### ISSUE THREAD

**Issue by Scienceseb** [d-ailin/GDN#23]
According to your code in TimeDataset.py you import a Scikit-learn module to do the normalization of the data, but it is never used. Don't you think it could be harmful for the model if there is a big difference in scale between the different measurements? 

Thanks !

Kind regards,
Sébastien de Blois

**Comment by d-ailin** [comment]
As the normalization has been moved to the preprocessing part, you could refer to the https://github.com/d-ailin/GDN/tree/main/scripts for the detail of preprocessing.
