### ISSUE TITLE
could give me some help? 

### ISSUE THREAD

**Issue by dh-jy** [d-ailin/GDN#26]
I'm sorry to bother you, I didn't run your code successfully. Could you give me some help?.
my steps are as follows:
1.git clone .........
2.bash install.sh
3.bash run.sh cpu msl
then error is coming
![image](https://user-images.githubusercontent.com/103489619/162910451-a260275c-b536-4184-9592-08a12e74b4c8.png)

And In your paper, how do you get the embedding vector of the sensor?
Thanks your for help

**Comment by dh-jy** [comment]
And in your code ,the marked function '(get_graph_struc()' i haven't found it 

![image](https://user-images.githubusercontent.com/103489619/162912712-304224b1-41db-4a0d-801e-c9ac40575b38.png)

**Comment by d-ailin** [comment]
Hi,

1. I am not quite sure how this error occurs, but I have found an issue related to your problem. Maybe it could help: https://github.com/pyg-team/pytorch_geometric/issues/1146 .
2. The embedding vectors of sensors are used in the Eq. (6) and (9), and later optimized with the Mean Squared Error.
3. The missing function here won't matter in the program. The function was previously used in some other trial experiments and I have removed it as it is not necessary for the current program.

**Comment by dh-jy** [comment]
Thank you very much for your reply. And I want to confirm whether the execution steps are wrong.
my steps are as follows:
1. git clone https://github.com/d-ailin/GDN.git
2. bash install.sh
3. bash run.sh cpu msl（or bash run.sh 1 msl ）

**Comment by dh-jy** [comment]
I found that you are from Singapore.Can you speak Chinese?

**Comment by d-ailin** [comment]
I think the commands are fine. Yes, I can. But if possible, let's text in English so that it could also be helpful for the others with the similar issues. 
Thanks!

**Comment by dh-jy** [comment]
Ok, thank you for your reply.

**Comment by d-ailin** [comment]
Closing. Feel free to reopen if there is any further question.
