### ISSUE TITLE
Did you perform data normalization in the experiment of your paper?

### ISSUE THREAD

**Issue by Jeong-Hyun-Woo** [d-ailin/GDN#27]
During the experiment on SWaT and WADI data, did you use normalization techniques such as min-max normalization?

**Comment by d-ailin** [comment]
Yes, we did. We used the min-max normalization in the preprocessing. You could refer to https://github.com/d-ailin/GDN/tree/main/scripts for more details.

**Comment by Jeong-Hyun-Woo** [comment]
Thank you for your reply.
