### ISSUE TITLE
CUDA version?

### ISSUE THREAD

**Issue by CaffreyR** [d-ailin/GDN#3]
Thank you for sharing the code.
One little question, does the CUDA version have to be 10.2?
Does the OSError has to do with the problem？
Thanks again

**Comment by d-ailin** [comment]
Hi, I haven't tried it with the latest CUDA version(e.g. 11.1), but I think it would be best to be 10.2 as some packages(e.g., torch-geometric) require a specific environment.

Maybe you could set up the environment with conda:
```
# CUDA 10.2
conda install pytorch==1.5.1 torchvision==0.6.1 cudatoolkit=10.2 -c pytorch
```

**Comment by CaffreyR** [comment]
> Hi, I haven't tried it with the latest CUDA version(e.g. 11.1), but I think it would be best to be 10.2 as some packages(e.g., torch-geometric) require a specific environment.
> 
> Maybe you could set up the environment with conda:
> 
> ```
> # CUDA 10.2
> conda install pytorch==1.5.1 torchvision==0.6.1 cudatoolkit=10.2 -c p

> Hi, I haven't tried it with the latest CUDA version(e.g. 11.1), but I think it would be best to be 10.2 as some packages(e.g., torch-geometric) require a specific environment.
> 
> Maybe you could set up the environment with conda:
> 
> ```
> # CUDA 10.2
> conda install pytorch==1.5.1 torchvision==0.6.1 cudatoolkit=10.2 -c pytorch
> ```

Thanks for replying.OSError occurs when importing libs, probably the version problem.
I will try again later.
Thanks again.
