### ISSUE TITLE
How to visualize the graph layout

### ISSUE THREAD

**Issue by 3rdTeaLatte** [d-ailin/GDN#30]
Hi, I'm very interested in your research. Thank you for your great paper.
Could you teach me how to visualize a learned graph layout?
I want to output a directed graph with attention weights like Fig. 3 shown in your paper.

I extracted a learned graph, attention weights and edge index from a learned best model by the following code.
```
learnd_graph = best_model.learned_graph
att_weight = best_model.gnn_layers[0].att_weight_1
edge_index = best_model.gnn_layers[0].edge_index_1
```
     
But I don't know how to correspond a learned graph and attention weights because their dimensions are quite different.
I mean, att_weight and edge_index have more edges than expected.
Is the referenced variable wrong?
       
It would help me a lot if you provided the code to visualize the graph.
I'm looking forward your reply.

**Comment by d-ailin** [comment]
Thanks for your interest in our work!

The edge_index[:, i] contains edge_start_node_id and edge_end_node_id, corresponding to the att_weight[i]. The att_weight and edge_index has more expected edges as we compute in batches here, if you use batch=1 to run the code then you will get the edges for one graph. Some example codes look like this:

```
coeff_weights = model.gnn_layers[0].att_weight_1.cpu().detach().numpy()
edge_index = model.gnn_layers[0].edge_index_1.cpu().detach().numpy()
weight_mat = np.zeros((feature_num, feature_num))

 for i in range(len(coeff_weights)):
        edge_i, edge_j = edge_index[:, i]
        edge_i, edge_j = edge_i % feature_num, edge_j % feature_num
        weight_mat[edge_i][edge_j] += coeff_weights[i]

# Next, you could average weight_mat if you use batches or directly use the result if you only use batch=1. 

```
Hope it helps :)

**Comment by 3rdTeaLatte** [comment]
Thanks for your quick reply. I got it!
I understand the relation between the number of edges and batches.
The sample codes was very useful to me.
I think I can output the target graph.
I really appreciate it!

**Comment by adverbial03** [comment]
I would like to know if the graph structure is fixed after the training is completed, will atti_weight and the graph structure not change during the test phase?
