### ISSUE TITLE
Varying number of sensors at each time step

### ISSUE THREAD

**Issue by TheNeeloy** [d-ailin/GDN#31]
Hi, I think your work is really awesome! 

I am working in an anomaly detection domain where the number of sensor sources at each time step may be different. For example, in the world, there may be sensors A, B, C, and D. From time steps 1 to 5, I may only be able to access to sensors A and B. Whereas from time steps 6 to 8, I may only have access to sensors B, C, and D. 

My understanding is that your current architecture directly works on a static number of sensors sources at each time step (both in training and testing). Is your architecture able to model a varying number of sensors at each time step?

Also, would you have any suggested readings or resources that helped you to gain a deep understanding of graphical neural networks and graph structure learning in general?

**Comment by d-ailin** [comment]
Thanks for your interest in our work!

I think our current model architecture can not adapt to a varying number of sensors at different time steps, but I think it is an interesting problem, and you could try to modify based on the current model or propose a new one.

For me, I think one reading resource is the papers included in https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#models. The code implementation insides can also be helpful for the understanding or the practical implementation. But I would say that is just my personal recommendation, as there are so many other helpful GNN related materials :D.

**Comment by TheNeeloy** [comment]
Thank you for your quick response! The problem area I am working in is anomaly detection on highways, conditioned on vehicle trajectories on the road. Here, the number of vehicles near the human-controlled vehicle may change from time-to-time when cars move in and out of our sensor range. If interested, I'll be sure to share my work in anomaly detection with varying sensor numbers after I submit, if it would help with your work too :)

Also, thanks for the resource; this will help me out a lot!

**Comment by d-ailin** [comment]
Sure, thanks :)
