### ISSUE TITLE
Some questions about the paper

### ISSUE THREAD

**Issue by Luca1236a** [d-ailin/GDN#34]
Hi, thank you so much for your wonderful work!
I'm working on Anomaly Detection too, but I'm a beginner in graph network. I have 2 questions:
1. About the sensor embedding, each vector _v_ represent a sensor. So, with the window size = 5 as in your paper, vector _v_ represents one sensor in the whole 5 timepoints, right? If my understanding is correct, can we apply your method to dynamic window size instead of using a fixed value of window size?
2. In Eq.7 in the paper, I'm still not clear about _a_ (a vector of learned coefficients for the attention mechanism). Can you explain a little bit more about _a_? How can we get it?

Sorry if I asked dummy questions. I'm looking forward to your reply!
Thank you so much!

**Comment by d-ailin** [comment]
Thanks for your interest in our work.

1. No. The vector v should be taken as a global sensor embedding for a sensor, and its dimension can be any predefined dimension number d. The window size is corresponding to the input size in Eq. (4). I think the current method can not be applied to dynamic window size directly, as the parameter W's shape is determined by the window size.
2.  For the attention mechanism, you can take a as an indicator of the importance of node j's features to node i's. You can also find more details in GAT https://arxiv.org/pdf/1710.10903.pdf.

**Comment by CongDo0820** [comment]
Thank you so much for the answer!
