### ISSUE TITLE
Some questions about Attention weights

### ISSUE THREAD

**Issue by LiPYlpy** [d-ailin/GDN#35]
Hello, thanks for sharing your excellent work!
May I ask how to get the attention weights for each edge? I want to try to draw Figure 3 ( Left ).
Another question is about using directed graphs for anomaly localization. As mentioned in the paper, 1_FIT_001_PV is the attacked object, and 1_MV_001_STATUS is detected as abnormal, and we are checking the weight of the edge pointed to 1_MV_001_STATUS (neighbor-->1_MV_001_STATUS). Do we need to check edges (1_MV_001_STATUS-->neighbor) which have high attention weights? Is this the point of the model using a directed graph?
Thank you very much!

**Comment by d-ailin** [comment]
1. You could refer to the previous issue #30 for the attention weight visualization. 
2. We take it as a directed graph. Yes, you could use the first setting you mentioned: using the abnormal sensor as the target and trace back the neighbors.

**Comment by LiPYlpy** [comment]
Thanks a lot for your answer!
