### ISSUE TITLE
Question about remove_self_loops and add_self_loops

### ISSUE THREAD

**Issue by TMaddox** [d-ailin/GDN#43]
Thank you for your excellent work!

I do have a question regarding your implementation of your graph_layer. Why do you need the following three lines?

https://github.com/d-ailin/GDN/blob/9853899da860682669a134e4af315d036aab4eca/models/graph_layer.py#L61-L63

Thanks!

**Comment by d-ailin** [comment]
These lines aim to remove the potential self_loops in the edge_index input and ensure there only exist one self_loop for a node. You could also refer to the similar implementation in the https://pytorch-geometric.readthedocs.io/en/1.5.0/_modules/torch_geometric/nn/conv/gat_conv.html.
