### ISSUE TITLE
The question about result 

### ISSUE THREAD

**Issue by fuyuyuputao** [d-ailin/GDN#45]
Hi, when I running main.py, I find that the result is unstable. After tried many times of main.py, I only got a few results consistent with the paper finally. I don't know this phenomenon is normal or not. Thanks a lot!
![1](https://user-images.githubusercontent.com/79823933/188301197-88538294-f1af-4475-8e49-4ed713c6748d.png)
![2](https://user-images.githubusercontent.com/79823933/188301206-36639178-1145-4b2e-b3ee-58f66cdd9916.png)
![3](https://user-images.githubusercontent.com/79823933/188301211-b092314c-5509-408c-aa36-ca8ba3a5f678.png)
And this is the parameter I used in main.py
![VIASEV$%5UOI@RCJGZDS%84](https://user-images.githubusercontent.com/79823933/188301283-1814fb08-c2f7-4e04-9de4-093394e257ed.png)

**Comment by gedizxc** [comment]
Hello, friend, excuse me, do you use the complete original data to get the result, or the partially processed data provided in the code

**Comment by fuyuyuputao** [comment]
Hello, I use complete original data from the https://itrust.sutd.edu.sg/itrust-labs_datasets/ and process original data by the process_swat.py.
![5JJF{{CJ@A6M5S%DM%X ~N](https://user-images.githubusercontent.com/79823933/188302466-7a06c7e9-48b4-4483-b6f3-d352d38971e6.png)

**Comment by d-ailin** [comment]
Hi @fuyuyuputao, thanks for your interest in our work.

I think the overall results you showed look fine to me. We have also found there exist some randomness even though the random seeds are set and fixed.

**Comment by fuyuyuputao** [comment]
OK! Thanks a lot!

**Comment by yangfan12311** [comment]
Hello, my friend, I got the original dataset from itrust and processed it, but the result doesn't seem to be as good as yours, can you please share the dataset, thanks a lot, my email is






> OK! Thanks a lot!

Hello, my friend, I got the original dataset from itrust and processed it, but the result doesn't seem to be as good as yours, can you please share the dataset, thanks a lot, my email is gs3000001@gmail.com！

**Comment by DavidDong004** [comment]
Hello, I got the original dataset from itrust and processed it, but the result doesn't seem to be as good as yours, could you please share the dataset, thanks a lot, my email is dzw1059169580@outlook.com
