### ISSUE TITLE
The question about abnormal recall and precision

### ISSUE THREAD

**Issue by andyclsr** [d-ailin/GDN#47]
Hi, thanks for your excellent work and release your code.
Below are based on the experiments on dataset wadi.
I was confused about the recall and precision shown in my experiments  all the time. The recall was always much higher than precision and even though I try other combination of the parameters.
I was unsure whether it lay in my handcraft labling on the test data, so i also use the processed data kindly provided by you. But the result remained the same.
By the way, I am also confused about the way I dealt with dataset, since I just read the attack document you provided and simply set the "attack" to 1 if it is during the time when an anomaly happend as the document described.
I don't know whether it is the correct way to deal with this :(
![image](https://user-images.githubusercontent.com/69943589/191266467-abb0cbee-e31f-4b96-a644-c828fd6f3340.png)

look forward to your reply!

**Comment by d-ailin** [comment]
Hi, I haven't come across this issue before. The provided processed data is collected from part of data as demo to help you to check, and the performance on it may not be valuable. Maybe you could check your processed data with the processed demo data to see if you have dealt with the data with proper preprocessing. Thanks.

**Comment by peerschuett** [comment]
Hi @andyclsr, did you solve this problem? :)

**Comment by andyclsr** [comment]
> Hi @andyclsr, did you solve this problem? :)



> Hi, I haven't come across this issue before. The provided processed data is collected from part of data as demo to help you to check, and the performance on it may not be valuable. Maybe you could check your processed data with the processed demo data to see if you have dealt with the data with proper preprocessing. Thanks.

The problem has been solved in Sep but i forgot to close the problem :(
thanks to your generous advice :) @d-ailin
