### ISSUE TITLE
Question about WADI dataset

### ISSUE THREAD

**Issue by WonmoKoo** [d-ailin/GDN#49]
Hello, I have question about WADI dataset. 
I requested WADI dataset to iTrust and will follow your preprocessing steps. 
There two versions of WADI dataset, WADI.A1_9 Oct 2017 and WADI.A2_19 Nov 2019, and table_WADI.pdf for both versions.

Q1. I think you used the former version (WADI.A1_9 Oct 2017), is it right?
Q2. In the attack description document for the version (table_WADI.pdf), the start date of the 9th attack is 10/10/17 10:55:00, but I think it's a typo. In your implementation, are the start and end time of the 9th attack 11/10/17 10:55:00 and 11/10/17 10:56:27, respectively?

**Comment by peerschuett** [comment]
Hi, how did you resolve this? Did you change the date for the 9th attack? I am labelling the data right now as well.

**Comment by WonmoKoo** [comment]
Yes, I changed the date for 9th attack! I was also confirmed by the author.

**Comment by WonmoKoo** [comment]
> Hi, how did you resolve this? Did you change the date for the 9th attack? I am labelling the data right now as well.

Yes, I changed the date for the 9th attack! I was also confirmed by the author.

**Comment by peerschuett** [comment]
Thanks a lot for the fast response!
