### ISSUE TITLE
alpha = softmax(alpha, edge_index_i, size_i)

### ISSUE THREAD

**Issue by wjj5881005** [d-ailin/GDN#5]
When I run the code, the above line is wrong, I think it should be "alpha = softmax(alpha, edge_index_i, num_nodes=size_i)"?

**Comment by d-ailin** [comment]
I think it could probably refer to #2

**Comment by d-ailin** [comment]
Thanks for your attention. 
Yes. Different versions might have specific changes on them, so I think using the correct version could be a safe(or best) choice :).
