### ISSUE TITLE
High losses

### ISSUE THREAD

**Issue by Andred00** [d-ailin/GDN#76]
Hi, I'm trying to use your GDN implementation (very great work!) but I think I am making some mistakes.
My loss values are very high, this cause me to have a lot of false positives when I try to test my model on the test set. What can the problem be?

**Comment by d-ailin** [comment]
The high losses indicate the model could not well predict the time series. I think it could be improved by preprocessing the data, such as min-max scaling or tuning some other hyperparameters (e.g. slide_win, etc) to see.
