### ISSUE TITLE
Question about MSL and SMAP dataset

### ISSUE THREAD

**Issue by peerschuett** [d-ailin/GDN#82]
In your code, you are using parts of the MSL dataset as an demo example for your method. How did you match the timestamps of all the different sensors? 
I took a look at the original data and the authors explicitly state that the timestamps (https://github.com/khundman/telemanom/issues/8#issuecomment-557706082) don't align and the values can't therefore be stacked on each other. How did you achieve this then?

**Comment by d-ailin** [comment]
Thanks for your question. 

We just made the toy data based on part of MSL's original data. It means the provided MSL is merely provided as demo data to check the environment (#15), or you could take it as toy data instead of an official evaluation of MSL. Sorry for any confusion it might cause.

**Comment by peerschuett** [comment]
Thanks a lot for the fast answer and sorry for my late reply! This solves my confusion. Having a toy dataset for a demo is a real good idea :)
