### ISSUE TITLE
multi-step prediction with iteration

### ISSUE THREAD

**Issue by FortunateStarstar86** [d-ailin/GDN#90]
I'm sorry to bother you with a problem I can't solve.
when I manipulate the input iteratively by appending the predicted value at T time step, and use the new input to predict the values at T+1,the Losses have increased exponentially.
![32333f5eb5cd604889847e35d54e53c](https://github.com/d-ailin/GDN/assets/69461421/f4955ef6-0f23-494b-b0dd-cb7e14e1897e)
I used the trained model test data (test.csv) to output "predicted", which resulted in exponentially larger predictions from the fourth round. Can you give some analysis or advice?
![f3bce4f16e0f5a4bfbed8e5bc10d02c](https://github.com/dailin/GDN/assets/69461421/cc9a40dc-7ac4-450e-88b1-017b9c919e6d)
Looking forward to your reply!

**Comment by FortunateStarstar86** [comment]
the second pic:
![f3bce4f16e0f5a4bfbed8e5bc10d02c](https://github.com/d-ailin/GDN/assets/69461421/24c3c16c-7094-496e-b62a-b61787b67e14)

**Comment by d-ailin** [comment]
Hi, i see. I guess it might be due to the error propagation in the sequential modeling, but it seems a bit severe from your cases. In this case, you might want to use more time steps as input, or try the way of training with an output of 10 dimensions. Sorry for the inconvenience.

**Comment by FortunateStarstar86** [comment]
> Hi, i see. I guess it might be due to the error propagation in the sequential modeling, but it seems a bit severe from your cases. In this case, you might want to use more time steps as input, or try the way of training with an output of 10 dimensions. Sorry for the inconvenience.

OK，Thanks for your reply！
