### ISSUE TITLE
question of fully connected graph

### ISSUE THREAD

**Issue by 0nyoun9** [d-ailin/GDN#91]
hello! I would like to ask what is the role of the fully connected graph constructed at the beginning of the code? At first I thought it was providing the index for GDN, but later I found that it didn't seem to have any effect.

**Comment by d-ailin** [comment]
Yes, as the graph construction is based on the vector similarities, fully connected graph here is not providing information for training. It is just part of some previous experimental code, e.g., for the cases given prior graph structures. Thanks for pointing out.
