### ISSUE TITLE
Weights initialization

### ISSUE THREAD

**Issue by kaya0007** [d-ailin/GDN#92]
Hello, thank you for your excellent work!
If there is a strong correlation between certain nodes in my dataset and I want to use it as prior knowledge to initialize weights, where should I modify the code to initialize them? The main issue is that there is no direct relationship between weights and nodes, so I don't know where to start making modifications.
Looking forward to your reply!

**Comment by kaya0007** [comment]
These dimensions do not match the number of nodes. How can I modify weights based on node relationships？
![屏幕截图_20230302_111601](https://github.com/d-ailin/GDN/assets/165001941/41d43fe3-9426-470c-9033-aaff69369281)

**Comment by kaya0007** [comment]
These dimensions do not match the number of nodes. How can I modify weights based on node relationships？
![屏幕截图 2024-03-26 163643](https://github.com/d-ailin/GDN/assets/165001941/c7e2cd1c-fe3e-4428-a03f-df50d4310891)

**Comment by d-ailin** [comment]
Hi, I think this issue could probably be solved by: #16.

**Comment by kaya0007** [comment]
> Hi, I think this issue could probably be solved by: #16.

thanks for the reply
