### ISSUE TITLE
remove some of the 127 features from wadi dataset

### ISSUE THREAD

**Issue by kaya0007** [d-ailin/GDN#94]
Hi, thanks for your excellent work!
I want to reduce the size of the Wadi dataset. Can I remove any of the 127 features? Is it okay to keep only a part of them? Will this affect the attach label?

looking forward to your reply!

**Comment by d-ailin** [comment]
Yes, you could remove some of these, but it could potentially lead to performance drop as less information given. To do this, you could just modify the features.txt directly by deleting lines, the program will build the graph based on feature names in the features.txt.

**Comment by kaya0007** [comment]
> Yes, you could remove some of these, but it could potentially lead to performance drop as less information given. To do this, you could just modify the features.txt directly by deleting lines, the program will build the graph based on feature names in the features.txt.

thanks!
