### ISSUE TITLE
some question about the auc score

### ISSUE THREAD

**Issue by 0nyoun9** [d-ailin/GDN#95]
Hi, thanks for your excellent work!
I saw in your code that you calculate the AUC score using `gt_labels` and `total_topk_err_scores`.
`auc_score = roc_auc_score(gt_labels, total_topk_err_scores)`
Can I use `gt_labels` and `pred_labels` to calculate the AUC score

**Comment by d-ailin** [comment]
When you already have pred_labels (0 or 1), you should evaluate other metrics, like precision instead of AUC. AUC can be seen as an average performance metric under different thresholds (these thresholds will decide 0 or 1 labels).

**Comment by 0nyoun9** [comment]
> When you already have pred_labels (0 or 1), you should evaluate other metrics, like precision instead of AUC. AUC can be seen as an average performance metric under different thresholds (these thresholds will decide 0 or 1 labels).

i get it，thank you！
